site_name: Pipeline de Dados de Vendas

nav:
  - Introdução: index.md
  - Geração de Dados: generate_data.md

theme:
  name: material
  palette:
    primary: red
    accent: red
  language: pt

repo_name: "BrunoChiconato/estrutura_dados"
repo_url: "https://github.com/BrunoChiconato/workshop_estruturando_projeto_dados"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [".."]  # Adjust path to point to the project root
          options:
            show_root_toc_entry: false
